### ISSUE TITLE
Allow teh user to choose -s behaviour

### ISSUE THREAD

**Issue by annazhukova** [tothuhien/lsd2#11]
Hi Hien,

I have a full-genome alignment of length 3,985,129 and it's a shame to have it replaced by 1000 for the CI estimation, as the CIs I get are unreasonably large for the dates, e.g. 2015.26 [1995.59 - 2016.04]	while non-existant for the rates 1.47261e-06 [1.47261e-06; 1.47261e-06].

It would be better in my opinion to keep 1000 as a default but use the user-supplied value if it's available.

Cheers,
Anna

**Comment by tothuhien** [comment]
Hi Anna,
Sorry for the long delay (was in holiday). I've just updated this in the new commit. Could you try and let me know if adjusting sequence length can resolve the problem with confidence intervals in your data. 
Regards,
Hien

**Comment by annazhukova** [comment]
Hi Hien,

Yes, it works. Thanks a lot!

Anna
