### ISSUE TITLE
Outliers not being removed

### ISSUE THREAD

**Issue by annazhukova** [tothuhien/lsd2#12]
Hi Hien,

There seems to be a problem with outlier removal in LSD2 v1.4.2.3:
I'm running it as 
```bash
lsd2 -i {input_tree} -d {input_dates} -v 2 -c -s {sequence_length} -o {output_name} -f 1000 -e 3 
```
It detects 32 outliers but they are present in the output  {output_name}.date.nexus tree.

My tree and dates are [here](https://drive.google.com/open?id=1SurYK0cHoq9MwTglB1_Tdn_H9R0RR8rF).

**Comment by tothuhien** [comment]
Hi Anna,
Thank you for pointing it out. This bug actually related to the case when removing one of the outlier making the initial root lost. I've fixed that, so that it allows to remove all outliers anyway with a warning message.
Cheers, 
Hien

**Comment by annazhukova** [comment]
That's great. Thank you, Hien!
