### ISSUE TITLE
malloc: Incorrect checksum for freed object ...: probably modified after being freed

### ISSUE THREAD

**Issue by bqminh** [tothuhien/lsd2#13]
I cloned the github repo, complied and tried LSD2 with a simple example:

    ~/software/lsd2/src/lsd2 -i example.phy.treefile -r a -s 1998 -c

However, there is a crash:

```
TREE 1
*PROCESSING:
Reading the tree ... 
Using the median branch length 0.0981519 to adjust variances ...
Minimum branch length of time scaled tree was set to 0/365 = 0
Estimating the root position on all branches using fast method ...
lsd2(11564,0x1153f9dc0) malloc: Incorrect checksum for freed object 0x7fa3cdd06690: probably modified after being freed.
Corrupt value: 0x0
lsd2(11564,0x1153f9dc0) malloc: *** set a breakpoint in malloc_error_break to debug
Abort trap: 6
```

Interestingly, this does not always occur, only after a few runs.

Moreover, when I tried the homebrew version, everything works fine:

```
TREE 1
*PROCESSING:
Reading the tree ... 
Estimating the root position on all branches using fast methode ...
*WARNINGS:
- The results correspond to the estimation of relative dates when T[mrca]=0 and T[tips]=1
*RESULTS:
- Dating results:
 rate 0.298264, tMRCA 0, objective function 148.416

TOTAL ELAPSED TIME: 0.006538 seconds
```

Do you know what happened? The tree file is attached.
[example.phy.treefile.txt](https://github.com/tothuhien/lsd2/files/4412847/example.phy.treefile.txt)

Thanks!
Minh

**Comment by tothuhien** [comment]
Hi Minh,
Thanks for raising the issue. It was actually a bug in my latest commit when I added the new function. I've fixed it now. You can clone the repo and try again. Please let me know if there's any other issues.
Cheers,
Hien

**Comment by bqminh** [comment]
works perfectly now! thanks for quick reaction
