### ISSUE TITLE
Add functionality to include LSD2 as a library

### ISSUE THREAD

**Issue by bqminh** [tothuhien/lsd2#15]
It would be great being able to call LSD2 within another program, because it's often used as downstream analysis to tree reconstruction. So adding some API to call LSD2 as a library is desirable, which should meet the following:

1. Converting input/output to C++ stream:
One main issue is the input/output, which right now only works with files. It's better if the program allows to do input/output from memory to speed up the interface. However, this is not easy because LSD2 currently uses FILE data structure of C. 

One solution is to convert everything into C++ istream for input and ostream for output. This re-factoring would allow us to pass everything to the library via in-memory structure such as stringstream and don’t have to rely on external disc files.

2. Ensuring thread-safety:
The API should be thread safe as it might be called on different threads (e.g. to date many trees in parallel). So for example, the functions should not use global or static variables.

Is it possible to do that?

**Comment by tothuhien** [comment]
Thanks Minh for your suggestion. It's definitely a great idea, I'll do that before releasing the next version and let you know when it's ready.

Best regards,
Hien

**Comment by tothuhien** [comment]
Hi Minh, 

In the latest commit 2ca847f, besides adding some features, I've changed FILE to iostream,istream and remove global variables. Could you check if it works now and let me know if anything else needs to be adjusted. 

Thank you 
Hien

**Comment by bqminh** [comment]
Awesome! I'll check that and also try to adapt the calling from files to streams, so that it fits into iqtree.

**Comment by bqminh** [comment]
After some testing I think LSD2 now runs really well -> great job!

Another item to add here:

3. Make LSD2 compilable and run on Windows (in addition to Linux and Mac). 

This is done and my test executable runs well on Windows 7.

For point 2 about thread-safety: I couldn't check yet. My only point right now is to avoid using those "old" C functions that are not thread-safe. 

For example, the random number generator (`srand`) are not safe. But I think you have now changed that to the C++ standard library, right?

**Comment by tothuhien** [comment]
Thanks Minh for your work. It's also really nice that it runs on Windows now. I don't have experience in thread-safety so couldn't help much. But I no longer use srand. I'll try to see if there's anything else should be adjusted.

Hien
