### ISSUE TITLE
Accepting dates in ISO format

### ISSUE THREAD

**Issue by bqminh** [tothuhien/lsd2#18]
Right now the date file for `-d` option must contain dates as integer. 

Is it possible to accept dates in ISO 8601 format, such as "2020-04-17" for 17 April 2020?

This is a common format that people used to store the dates of the sample. It's quite handy, also many users wouldn't know how to convert back and forth to integers, that LSD supports.

Thanks!

**Comment by tothuhien** [comment]
I will consider doing that soon!

Cheers,
Hien

**Comment by tothuhien** [comment]
Hi, I've added this possibility in the commit 732626d. Moreover, the old version also accept reals for dates, not only integers. You can either put for example 2020.2931 or 2020-04-17 for 17 April 2020. Let me know if there's any issue in this commit. Thanks.
Hien

**Comment by bqminh** [comment]
Awesome, really appreciate that! I will try it out and let you know.
