### ISSUE TITLE
Negative branch lengths despite -c option

### ISSUE THREAD

**Issue by bqminh** [tothuhien/lsd2#19]
The command line is:

```
lsd -i example.phy.timetree.subst -s 1998 -c -o example.phy.timetree -g example.phy.timetree.outgroup -k 
```

I note that without the outgroup, everything seems fine.

Any idea why?
The tree and outgroup files are attached.

[example.phy.timetree.subst.txt](https://github.com/tothuhien/lsd2/files/4436017/example.phy.timetree.subst.txt)

[example.phy.timetree.outgroup.txt](https://github.com/tothuhien/lsd2/files/4436018/example.phy.timetree.outgroup.txt)

**Comment by tothuhien** [comment]
Thanks Minh. I also found that yesterday. It was a typo in the commit 405fa8a that caused that. It was fixed in the latest commit 887434b.

Cheers,
Hien
