### ISSUE TITLE
Better error message for all unknown dates

### ISSUE THREAD

**Issue by annazhukova** [tothuhien/lsd2#20]
Hi Hien,

I have a very corner-case example of a tree with a few tips and a date file that contains some dates for the ids that are **not** in the tree, and some very large date intervals **(all the same)** for the ids that are in the tree (arisen due to a naming problem ;) ).
I try to run LSD2 as follows:
```bash
lsd2 -i tree.nwk -d dates.tab -v 2 -c  -f 1000 -o tree_lsdated2 -r a -e 3 -s 1000
```
and obtain a segmentation fault:
```bash
TREE 1
*PROCESSING:
Reading the tree ... 
Parameter to adjust variances was set to 0.000684512 (settable via option -b)
Calculating the outlier nodes ...
Segmentation fault (core dumped)
```

What I would like to obtain instead is something like: "There are not enough temporal constraints provided to date this tree".

The tree and the dates are [here](https://drive.google.com/drive/folders/1SurYK0cHoq9MwTglB1_Tdn_H9R0RR8rF?usp=sharing).

**Comment by tothuhien** [comment]
Thanks Anna! It's indeed a case that I missed. I've fixed that in the latest commit 98f5b2d. Let me know if you find any other issues.

Cheers,
Hien
