### ISSUE TITLE
Segmentation fault with -g option

### ISSUE THREAD

**Issue by bqminh** [tothuhien/lsd2#21]
The command line was:
```
lsd2 -i aln.fa.timetree.subst -s 30285 -c -o aln.fa.timetree -g aln.fa.timetree.outgroup -k -d aln.fa.timetree.date
```

And screen output:

```
Removing outgroups of tree 1 ...
Segmentation fault: 11
```

Without -g option and add `-r a`, it works fine.

Any idea?

Thanks!

The input files are attached.

[aln.fa.timetree.subst.txt](https://github.com/tothuhien/lsd2/files/4460189/aln.fa.timetree.subst.txt)
[aln.fa.timetree.outgroup.txt](https://github.com/tothuhien/lsd2/files/4460190/aln.fa.timetree.outgroup.txt)
[aln.fa.timetree.date.txt](https://github.com/tothuhien/lsd2/files/4460192/aln.fa.timetree.date.txt)

**Comment by tothuhien** [comment]
Thanks Minh for reporting the this. This was a bug related to the commit 2ca847f. I've fixed that in the latest commit. 

Cheers,
Hien

**Comment by bqminh** [comment]
It works now, thanks for fixing it so quickly!
Moreover, there is a compiler warning:

`Variable 'medianRateOK' is used uninitialized whenever 'if' condition is false`

Do you think if this is of any concern?

**Comment by tothuhien** [comment]
Hi, thanks. There's normally no problem running the program with that warning; but you're right it's better to not have any warning when compiling. I'll fix that.
