### ISSUE TITLE
Allow YYYY-MM-DD for tip and root dates

### ISSUE THREAD

**Issue by bqminh** [tothuhien/lsd2#25]
With the new support of YYYY-MM-DD date format, can you please allow `-a rootDate` and `-z tipDate` to accept this format?

Also these options currently require integer. Can you relax this assumption, i.e. a real number is OK? 

Thanks a lot for your work, Hien!

**Comment by tothuhien** [comment]
Hi Minh. Indeed I forgot to allow the options -a and -z to have real number and new date format. Just added this in the new commit. Thanks for reminding this.

Cheers,
Hien

**Comment by bqminh** [comment]
Awesome, it works! thank you, Hien
