### ISSUE TITLE
More flexible date format

### ISSUE THREAD

**Issue by bqminh** [tothuhien/lsd2#28]
LSD allows the date format `YYYY-MM-DD`, which is very useful. thanks!

However, in my data there are some sample which dated `2020-01`, meaning that we don't have the exact day, and only know that it was sampled in Jan 2020. Is it possible for you to accept this format? 

I can of course pre-process the date again to the range from 2020-01-01 to 2020-01-31. But that's a bit tedious because different months have different number of days...

So can you allow `YYYY-MM`, just to specify the year and month of the sample? And internally LSD will convert it into a range and automatically account for uncertainty.

Also I have other samples with just YYYY, i.e. we only know the year of the sample. For example, 2019 really means the range from 2019-01-31 to 2019-12-31.

Is it also possible for accept this format? I know this is ambiguous. But perhaps if you see that at least another taxon has the date YYYY-MM-DD, then a simple YYYY would really mean that. Only when there is no YYYY-MM-DD for any taxa, then YYYY will really mean that number.

Sorry for a lot of requests... I'm just thinking about how to make LSD most user-friendly. Hopefully then people will come to use your software.

Thanks!

**Comment by tothuhien** [comment]
Hi Minh. Thanks for your suggestion. That makes sense. I'll consider adding this probably next week. 
Hien

**Comment by intikhab** [comment]
Hi Hien,

Were you able to add support for YYYY-MM-DD format of date to be considered when dating a tree? I tested it but it does not seem to work. 

bash-4.2$ singularity run docker://evolbioinfo/lsd2:v1.6.5 -i test.treefile -d tree.date.tsv -s 29000 -o test_lsd -r a -u 1 -U 1 -D 1

TREE 1
*PROCESSING:
Reading the tree ...
Error in the file tree.date.tsv : real or date format year-month-date expected
-bash-4.2$ head tree.date.tsv
9834
EPI402120 2020-01-01
EPI402121 2019-12-30
EPI402123 2019-12-24

Can you please have a look?

Thanks,

IA

**Comment by tothuhien** [comment]
Hi IA,
Normally version 1.6.5 should be able to handle with the date format year-month-date. Could you send me the whole tree.date.tsv file so I can check. Maybe there're some dates not in correct one or something that I didn't take into account.  Thanks.
Hien

**Comment by intikhab** [comment]
Hi Hien,

Yes, there is a mix of YYYY, YYYY-MM and YYYY-MM-DD style date information and the majority of dates are of the full YYYY-MM-DD format.

If you share your contact, I can send you my tree.date.tsv file.

Best,

IA

**Comment by tothuhien** [comment]
Hi, you can send it to my email:  tothuhien@gmail.com
Hien

**Comment by tothuhien** [comment]
Hi @bqminh and @intikhab ,

In the new commit, I've added the possibility to have mix date formats of year-month-day, year-month and year. Please let me know if there's any issue with this.

Kind regards,
Hien

**Comment by bqminh** [comment]
Awesome! thanks Hien.
