### ISSUE TITLE
Add example using the files in example/

### ISSUE THREAD

**Issue by tseemann** [tothuhien/lsd2#3]
Can you provide a comamnd line using the files in examples/ folder so I can write a test for the brew and conda packages?

**Comment by tothuhien** [comment]
Hi,  a command line using the files in examples folder could be:
`lsd2 -i examples/rooted_tree/h1n1_phyml.tree -d examples/rooted_tree/h1n1.date -c -v 1`
Thanks.
Hien

**Comment by tseemann** [comment]
Thanks, that is very useful!
I'll close this issue once I implement it.

**Comment by JLD1982** [comment]
Hey

**Comment by tseemann** [comment]
I have implemented this.

**Comment by tothuhien** [comment]
Thanks a lot!
