### ISSUE TITLE
Understanding date notation in date file

### ISSUE THREAD

**Issue by mkweskin** [tothuhien/lsd2#30]
Hi @tothuhien,
I'm looking at your examples for date notation in the date file and could use help getting this right for my analysis.

The example on the readme:
```
5			# number of temporal constraints
A 1999.2		# the date of A is 1999.2
B 2000.1		# the date of B is 2000.1
C l(1990.5)		# the date of C is at least 1990.5
D b(1998.21,2000.5)	# the date of D is between 1998.21 and 2000.5
mrca(A,B,C) u(2000.12)	# the date of the most recent ancestor of A,B, and C is at most 2000.12
```

I have an ancestral node that is the MRCA of a monophyletic group that is at least 48.7 MYA, but the max age is not know. Reading the example above, I would think that should be represented as `l(-48.7)`, the node is at least -48.7, but could be older (more negative).

In comparing runs of lsd2 where I use `l(-48.7)` and `u(-48.7)`, I think I have it backwards and I should be using `u(-48.7)`. `l(-48.7)` results in an estimated node age of `-48.7` from the analysis, but when I use `u(-48.7)` I get an estimated age that is older, `-157`.

Am I thinking about "at least" and "at most" in your examples backwards?
Thank you!

**Comment by tothuhien** [comment]
Hi Matthew,

Thanks for raising the issue. It's indeed confusing when using "at least", "at most" here in the context of negative dates. When I used "at least" I wanted to say >=, i.e more recent. I've edited that paragraph in the README file, hope it would be clearer.
Let me know if you think there's any other things not clear.
Cheers,

Hien

**Comment by mkweskin** [comment]
Thanks, I appreciate the clarification.
