### ISSUE TITLE
unrooted bifurcating tree dating could output multifurcating trees

### ISSUE THREAD

**Issue by zcrabbit** [tothuhien/lsd2#33]
I wonder if there is an option to restrict the output to be bifurcating rooted trees. I have tested options like -l 0.0 -u 0.0, but it can still produce multifurcating trees.

**Comment by tothuhien** [comment]
Hi @zcrabbit , I’m sorry I didn’t see your question. The option -u 0 force all branches to be at least 0, so the branch lengths of the output tree can be 0. If you don’t want null branches, you need a strict positive value to be specified with option -u. 
Cheers,
Hien
