### ISSUE TITLE
Date file with the format yyyy-mm-dd

### ISSUE THREAD

**Issue by sanjusare** [tothuhien/lsd2#34]
Dear Tothuhien,

How can I use a date file with the format:

tip_1    2020-01-15
tip_2    2020-02-26
tip_3    2019-12-31
tip_4    2020-06-45

to perform a dated tree?

**Comment by tothuhien** [comment]
Hi @sanjusare, the actual version of lsd2 can read directly this date format. Did you get any error when using this?
Hien

**Comment by BEAST-Community** [comment]
any update for the lsd version?

**Comment by tothuhien** [comment]
Hi, the actual version now is v.1.9.7 https://github.com/tothuhien/lsd2/releases/tag/v1.9.7
