### ISSUE TITLE
is this okay for me

### ISSUE THREAD

**Issue by BEAST-Community** [tothuhien/lsd2#35]
(base) lixingguangtekiMacBook-puro:bin lixingguang$ ./lsd2_mac -i 755.newick.tre -d 755.date -s 8462 -v 2 -f 1000

TREE 1
*PROCESSING:
Reading the tree ... 
Collapse 2 (over 753) internal branches having branch length <= 5.90877e-05
 (settable via option -l)
Parameter to adjust variances was set to 0.029848 (settable via option -b)
Minimum branch length of time scaled tree (settable via option -u and -U): 0
Dating under temporal constraints mode ...
Re-estimating using variances based on the branch lengths of the first run ...
Computing confidence intervals using sequence length 8462 and a lognormal
 relaxed clock with mean 1, standard deviation 0.2 (settable via option -q)
*RESULTS:
- Dating results:
 rate 0.00261091, tMRCA 1945.75 , objective function 0.910066
- Results of the second run with variances based on results of the first run:
 rate 0.00263291, tMRCA 1943.85, objective function 0.951829
- Results with confidence intervals:
 rate 0.00263291 [0.00237043; 0.00297681], tMRCA 1943.85 [1930.17; 1953.32], objective function 0.951829

TOTAL ELAPSED TIME: 58.9098 seconds
(base) lixingguangtekiMacBook-puro:bin lixingguang$

**Comment by tothuhien** [comment]
Hi, yes it looks good; but after that it depends what do you need, how's the inputs etc ...
