### ISSUE TITLE
Details about confidence intervals

### ISSUE THREAD

**Issue by Koohoko** [tothuhien/lsd2#37]
Hi Authors,

Thanks for your great work.
I am using IQ-TREE with default parameters to estimate the dates of the nodes. According to IQ-TREE: the confidence intervals are estimated based on a mixture of Poisson and lognormal distributions for a relaxed clock model.

May I know is it the 95% confidence interval or 99% confidence interval?

Thanks so much for your kind help.

**Comment by tothuhien** [comment]
Hi @Koohoko , it's the 95% confidence.
Cheers,
Hien

**Comment by Koohoko** [comment]
Thanks so much.

Thu-Hien To ***@***.***>于2022年1月24日 周一04:13写道：
