### ISSUE TITLE
Issue with CI calculation on a datafile with constraints on internal nodes (v2.3)

### ISSUE THREAD

**Issue by annazhukova** [tothuhien/lsd2#38]
Hi Hien,

I have tried to redo an old analysis (which worked with lsd2 v1.4.2.2) and run into the segmentation fault.

Here is the tree: [rooted_tree.nwk](https://github.com/evolbioinfo/HIV1-CRF19_Cuba/blob/main/data/datasets/D_CRF_19/rooted_tree.nwk) and the dates file: [lsd2.dates](https://github.com/evolbioinfo/HIV1-CRF19_Cuba/blob/main/data/datasets/D_CRF_19/lsd2.dates), which has some constraints on some internal nodes, looking like: 
```
mrca(CU2281-16,CU443-12)	b(1900,2008.62977767797)
```

With lsd2 v1.4.2.2, I was running the following command (successfully):
```
lsd2 -i rooted_tree.nwk -d lsd2.dates -v 2 -c -s 3894 -e 3 -f 100
```
With lsd v2.3, I can run the dating without CIs with no problem:
```
lsd2 -i rooted_tree.nwk -d lsd2.dates -v 2 -s 3894 -e 3
```
However, adding CIs (-f 100):
```
lsd2 -i rooted_tree.nwk -d lsd2.dates -v 2 -s 3894 -e 3 -f 100
```
leads to the following error:
```
TREE 1
*PROCESSING:
Reading the tree ... 
Collapse 23 (over 384) internal branches having branch length <= 0.000128403
 (settable via option -l)
Parameter to adjust variances was set to 0.013743 (settable via option -b)
Calculating the outlier nodes with Zscore threshold 3 (setable via option -e)...
Minimum branch length of time scaled tree (settable via option -u and -U): 0
Dating under temporal constraints mode ...
Re-estimating using variances based on the branch lengths of the first run ...
Computing confidence intervals using sequence length 3894 and a lognormal
 relaxed clock with mean 1, standard deviation 0.2 (settable via option -q)
Segmentation fault (core dumped)
```

If I remove the constraints from the date file, everything works smoothly.

Cheers,
Anna

**Comment by tothuhien** [comment]
Thanks Anna for reporting, I'm looking at this.
Cheers,
Hien

**Comment by tothuhien** [comment]
Hi Anna. Sorry for take it long. I have tried to fix the bug and just updated the code on the main branch. Could you try again and let me know?
Hien

**Comment by annazhukova** [comment]
Thanks a lot Hien! It all works well now.
