### ISSUE TITLE
Option -n broken

### ISSUE THREAD

**Issue by Lars-B** [tothuhien/lsd2#39]
I stated the problem [here](https://github.com/tothuhien/Rlsd2/issues/2#issue-1691685924), initially I thought it was a problem of the R wrapper.

Any version after 1.7.1 breaks when using -n != 1.
This problem carries over to IQtree and the R version.

**Comment by tothuhien** [comment]
Hi,
Thanks for reporting, and sorry for the late response. This option is only used for the set of tree having the same set of leaf labels. Do your trees have that? If they do, so maybe another issue, then it would be useful if you can send me the data to debug. I have tested on our simulated data and it does not have any problem. 
Best regards,
Hien

**Comment by Lars-B** [comment]
Hey Hien,

The trees do have the same leaf labels as they are one bootstrap samples from IQtree.
I attached a sample of trees, the alignment and a screenshot of what my current problem looks like.

- LSD2 1.7.1 works on Mac os using the Homebrew install or the precompiled donwload.
- Using a Linux machine 1.7.1 returns a segmentation fault.
- Using 2.4.1 on Linux or Mac returns the reported error, same when I try to use IQtree

Thanks for the help!
[LSD2-issue.zip](https://github.com/tothuhien/lsd2/files/11390451/LSD2-issue.zip)

**Comment by tothuhien** [comment]
Hi Lars. Thanks for sending me the data that helped me to find the issue, which instead of having all trees, it just retained the last one. I just fixed it now on the master branch. Could you try again?
Best regards,
Hien

**Comment by Lars-B** [comment]
Yes, It works now.
Thank you!
