### ISSUE TITLE
date format

### ISSUE THREAD

**Issue by csavin75** [tothuhien/lsd2#8]
Hi,

Could you tell me how to format the file with the dates?
It works with the year but I don't understand how to format the date with months and possibly the day?
Thanks,

Cyril

**Comment by tothuhien** [comment]
Hi Cyril,
A date should be a real number. So if your date is for example 15 June 2019, which is about 166 days after 2019, then you have 2019+(166)/365  -> 2019.4548. 
Cheers,
Hien
