### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by annazhukova** [tothuhien/lsd2#9]
Dear Hien,
I'm trying to run the latest versions of LSD2 (1.4.2, 1.4.2.1) and getting a segmentation fault:
```bash
> lsd2 -i ./rooted_tree.nwk -d ./lsd2.dates -v 2 -c -s 3512 -f 1000 -o ./lsd2_wd -e 3

TREE 1
*PROCESSING:
Reading the tree ... 
Calculating the outlier nodes ...
Segmentation fault (core dumped)
```
while the previous version (1.4) was working fine on the same data (available [here](https://drive.google.com/drive/folders/17ZMV3U1aDnENQfQdbeu_p4fsjMUAYJJS?usp=sharing)).

**Comment by tothuhien** [comment]
Hi Anna,
Thank you very much for reporting the bug. I've fixed that in the new version. Please let me know if you have more errors.
Cheers,
Hien

**Comment by annazhukova** [comment]
Thanks Hien, it works perfectly in the new version!
